### PR TITLE
Add testnet Explorer and some Endpoints from NodeStake

### PR DESCRIPTION
**Pull request by nodestake**

### CODE REVIEW

**Comment by onsails** [comment]
Thanks! Please describe your endpoints. Which is which.

Tendermint gRPC/Rest
Cosmos gRPC/Rest
EVM

**Comment by onsails** [comment]
Also, in explorer url it's better to call network haqq-testedge, since we are going to have two separate testnets: TestEdge (upcoming features testing) and TestNow (mainnet-equivalent).

**Comment by nodestake** [comment]
> Also, in explorer url it's better to call network haqq-testedge, since we are going to have two separate testnets: TestEdge (upcoming features testing) and TestNow (mainnet-equivalent).

The current chain(haqq_53211-1) is called haqq-testedge?
The new testnet chain will be called TestNow?

**Comment by onsails** [comment]
> > Also, in explorer url it's better to call network haqq-testedge, since we are going to have two separate testnets: TestEdge (upcoming features testing) and TestNow (mainnet-equivalent).
> 
> The current chain(haqq_53211-1) is called haqq-testedge? The new testnet chain will be called TestNow?

Yep.

**Review by onsails — APPROVED** [review]

**Pull request merged**
